### PR TITLE
Fixes to the stopCurrentService to sleep in a low power way

### PR DESCRIPTION
**Pull request by jaustin**
This is an update of Andres and Jan's branch that adds yt config support and introduces a way for a programme to stop the beacon from advertising and sleep gracefully

### CODE REVIEW

**Comment by pan-** [comment]
Looks OK to me, the build from our CI work as expected.

**Comment by pan-** [comment]
retest this please.

**Comment by jaustin** [comment]
Hi @pan- - what's the status of this - are you or @andresag01 happy to merge it?

**Comment by pan-** [comment]
As I said, I am but I don't know if @andresag01 is happy with it.

**Comment by andresag01** [comment]
I am happy with these changes.

**Comment by pan-** [comment]
retest this please.

**Pull request merged**
